spring.datasource.url=jdbc:mysql://localhost:3306/tshirt_platform
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
clipdrop.api.key=bef7f057cd26bb3e865306a9ed61e4b5dcbcbcc94685af02408462d14b3d4e6e8920a180c9bccf9c6f6979ec40c1a344

server.port=8080